<?php

/**
 * @file
 * Core hooks for amazons3_override.
 */

define('S3_SCHEME', 's3');

/**
 * Implements hook_field_default_field_bases_alter().
 */
function amazons3_override_field_default_field_bases_alter(&$info) {
  foreach ($info as $delta => $field) {
    if (!empty($field['settings']['uri_scheme'])) {
      $info[$delta]['settings']['uri_scheme'] = S3_SCHEME;
    }
  }
}

/**
 * Implements hook_field_default_field_bases_alter().
 */
function amazons3_override_field_default_field_instances_alter(&$info) {
  foreach ($info as $delta => $field) {
    $types = array(
        'file_generic',
        'media_generic',
    );
    if ($field['widget'] &&
        in_array($field['widget']['type'], $types)) {
      $info[$delta]['widget']['settings']['allowed_schemes'][S3_SCHEME] = S3_SCHEME;
    }
  }
}
